title: Automated Theory Construction
email: "milanotukamoto@g.ecc.u-tokyo.ac.jp"
description: >-
  Research notes and posts for the Automated Theory Construction project.
baseurl: "/automated-theory-construction-lean"
url: "https://tukamilano.github.io"
github_username: tukamilano
timezone: Asia/Tokyo

theme: minima
plugins:
  - jekyll-feed
